export const experienceData = [
  {
    date: 'Aug 2024 - up to today',
    organization: 'DEX technologies',
    href: 'https://dex-it.ru/',
    position: 'Frontend Engineer',
    description: [
      'Support and development of multiple projects: fixing bugs, improving existing functionality, and developing new features',
      'Initiated the development of two projects, selection of necessary technologies',
      'I successfully migrated the in-app chat system to a new architecture based on Matrix Synapse.',
      'Updating dependencies to the latest versions, improving security and stability',
      'Integration of TypeScript, improving code readability, simplifying refactoring, and reducing errors',
      'Optimizing bundle size, reducing file weight for faster loading',
      'Implementing modern architecture (FSD) and refactoring the code, making the project more scalable',
      'Provided assistance and conducted code reviews for junior developers in the team.',
      'Using Zustand for efficient and easy local state management',
      'Enhancing Developer Experience (DX): configuring linters, formatters, and automating development processes',
    ],
    chips: [
      'React',
      'Next.js',
      'Zustand',
      'TanStack Query',
      'Ant Design',
      'SCSS',
      'Redux',
      'TypeScript',
      'Chart js',
      'MUI',
      'i18n',
    ],
  },
  {
    date: 'Oct 2022 - Jun 2024',
    organization: 'Aeroidea',
    href: 'https://aeroidea.ru/',
    position: 'Frontend Engineer',
    description: [
      'Developed an audio player for language learning materials.',
      'Implemented code autogeneration tools to streamline development.',
      'Added and documented UI components in Storybook.',
      'Addressed the needs of users with disabilities: implemented themes with high contrast, as well as options for increasing font sizes and letter spacing.',
      'Wrote unit tests to ensure component reliability.',
      'Built a product card slider with media support and user-generated content.',
      'Provided assistance and conducted code reviews for junior developers in the team.',
      'This allowed administrators to create unique pages for different events, promotions, and advertising campaigns, and remove them when no longer needed.',
      'Performed fine-tuning of page caching for faster page load times.',
    ],
    chips: [
      'Next.js',
      'Zustand',
      'TanStack Query',
      'SCSS',
      'TypeScript',
      'Storybook',
      'Jest',
      'React testing library',
    ],
  },
]
